import path from "node:path";
import { CATALOG_DIRS, SCHEMA_VERSION } from "./constants.js";
import { readTextSafe, uniqueSorted } from "./fs-utils.js";
import type { CapabilityManifest, CatalogManifest, Confidence, Maturity, RiskManifest, ScanArtifact } from "./types.js";

const MAX_EVIDENCE_PATHS = 30;

interface CapabilitySeed {
  id: string;
  name: string;
  type: string;
  summary: string;
  source_paths: string[];
  api_routes?: string[];
  ui_components?: string[];
  dependencies?: string[];
  external_services?: string[];
  env_vars?: string[];
  reads?: string[];
  writes?: string[];
  sensitive_data?: string[];
  persistence_layer?: string[];
  validation?: string[];
  auth_requirements?: string[];
  maturity?: Maturity;
  confidence?: Confidence;
  reuse?: CapabilityManifest["reuse"]["reusable"];
  extraction_difficulty?: CapabilityManifest["reuse"]["extraction_difficulty"];
  notes?: string[];
}

export function buildBootstrapCatalog(scan: ScanArtifact, scanArtifactPath?: string): CatalogManifest {
  const repoMaturity = inferRepoMaturity(scan);
  const repoConfidence = inferRepoConfidence(scan);
  const repoDescription = inferDescription(scan);
  const repositoryRisks = buildRepositoryRisks(scan);
  const capabilities = buildCapabilities(scan, repositoryRisks);
  const docsPresent = scan.docs.readme_paths.length > 0 || scan.docs.doc_paths.length > 0;

  return {
    schema_version: SCHEMA_VERSION,
    repo: {
      id: scan.repo.id,
      name: scan.repo.name,
      path: scan.repo.path,
      remote_url: scan.repo.remote_url,
      description: repoDescription,
      primary_language: scan.languages[0]?.language ?? null,
      languages: scan.languages.map((language) => language.language),
      frameworks: scan.frameworks.map((framework) => framework.name),
      package_manager: scan.packages.package_manager,
      databases: scan.database.databases,
      deployment: inferDeployment(scan),
      maturity: repoMaturity,
      confidence: repoConfidence,
      scan_artifact: scanArtifactPath ?? `catalog/scans/${scan.repo.id}.scan.json`,
      analyzed_at: new Date().toISOString()
    },
    capabilities,
    repository_risks: repositoryRisks,
    catalog_quality: {
      coverage: {
        scan_artifact: true,
        readme: scan.docs.readme_paths.length > 0,
        docs: docsPresent,
        routes: scan.routes.api_routes.length > 0 || scan.routes.app_routes.length > 0,
        tests: scan.tests.length > 0,
        llms_context: scan.docs.llms_context_paths.length > 0
      },
      missing_evidence: inferMissingEvidence(scan),
      uncertainty_notes: [
        "Generated by evidence-bound bootstrap analyzer. Run with CATALOG_USE_CODEX=1 for schema-constrained Codex interpretation.",
        ...(scan.docs.llms_context_paths.length ? ["Local LLMs files were included as context evidence, not treated as code behavior proof."] : [])
      ],
      validation_status: "unvalidated",
      validated_at: null
    }
  };
}

function buildCapabilities(scan: ScanArtifact, repositoryRisks: RiskManifest[]): CapabilityManifest[] {
  const seeds: CapabilitySeed[] = [];
  const allDependencies = mergedPackageNames(scan);
  const readmePaths = scan.docs.readme_paths.map((file) => file.path);
  const docsPaths = [...scan.docs.readme_paths, ...scan.docs.doc_paths].map((file) => file.path);
  const llmsPaths = scan.docs.llms_context_paths.map((file) => file.path);
  const testPaths = scan.tests.map((test) => test.source_path);
  const envVars = scan.env.variables.map((variable) => variable.name);
  const externalServices = scan.integrations.map((integration) => integration.name);
  const sensitiveData = scan.security.sensitive_data_indicators.map((indicator) => indicator.name);

  if (scan.routes.api_routes.length) {
    seeds.push({
      id: "api.route-handlers",
      name: "API Route Handlers",
      type: "api",
      summary: "Repository exposes source-backed API route handlers discovered from framework route files.",
      source_paths: scan.routes.api_routes.map((route) => route.source_path),
      api_routes: scan.routes.api_routes.map((route) => `${route.methods.join("|")} ${route.route}`),
      dependencies: allDependencies,
      external_services: externalServices,
      env_vars: envVars,
      reads: ["HTTP requests"],
      writes: scan.routes.api_routes.some((route) => route.methods.some((method) => method !== "GET" && method !== "HEAD")) ? ["HTTP responses", "possible state changes from non-GET routes"] : ["HTTP responses"],
      sensitive_data: sensitiveData,
      validation: allDependencies.includes("zod") ? ["zod dependency detected"] : [],
      auth_requirements: authRequirements(scan),
      confidence: "high",
      reuse: "partial",
      extraction_difficulty: scan.frameworks.length ? "medium" : "unknown"
    });
  }

  if (scan.routes.app_routes.length) {
    seeds.push({
      id: "routing.application-pages",
      name: "Application Routes",
      type: "routing",
      summary: "Repository contains user-facing application page routes.",
      source_paths: scan.routes.app_routes.map((route) => route.source_path),
      api_routes: scan.routes.app_routes.map((route) => `GET ${route.route}`),
      dependencies: allDependencies,
      reads: ["route parameters", "rendered application state"],
      writes: ["HTML or client-rendered UI"],
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "medium"
    });
  }

  if (scan.components.length) {
    seeds.push({
      id: "ui.component-library",
      name: "UI Component Library",
      type: "ui-component",
      summary: "Reusable UI components were found in component-oriented source paths.",
      source_paths: scan.components.map((component) => component.source_path),
      ui_components: scan.components.map((component) => component.name),
      dependencies: allDependencies,
      reads: ["component props", "application state"],
      writes: ["rendered UI"],
      sensitive_data: sensitiveData.filter((item) => ["email", "password", "token", "payment", "pii"].includes(item)),
      confidence: "medium",
      reuse: "partial",
      extraction_difficulty: scan.frameworks.some((framework) => ["React", "Svelte", "Vue"].includes(framework.name)) ? "medium" : "unknown"
    });
  }

  if (scan.database.schemas.length || scan.database.migrations.length || scan.database.databases.length) {
    seeds.push({
      id: "database.schema-management",
      name: "Database Schema Management",
      type: "database",
      summary: "Repository includes database schemas, migrations, or database framework dependencies.",
      source_paths: [...scan.database.schemas, ...scan.database.migrations].map((file) => file.path).concat(packageEvidence(scan)),
      dependencies: allDependencies,
      reads: ["database schema definitions"],
      writes: scan.database.migrations.length ? ["database migrations"] : [],
      sensitive_data: sensitiveData,
      persistence_layer: scan.database.databases,
      confidence: scan.database.schemas.length || scan.database.migrations.length ? "high" : "medium",
      reuse: "partial",
      extraction_difficulty: "high"
    });
  }

  if (scan.discovery_files.llms.length) {
    seeds.push({
      id: "discovery.llms-files",
      name: "LLMs Discovery Files",
      type: "discovery",
      summary: "Repository provides local LLMs discovery/context files that can guide machine-readable understanding.",
      source_paths: scan.discovery_files.llms.map((file) => file.path),
      reads: ["repository-provided LLMs context"],
      writes: ["machine-readable discovery context"],
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "low",
      notes: ["Use as context for interpretation; verify behavioral claims against source files."]
    });
  }

  if (scan.discovery_files.openapi.length) {
    seeds.push({
      id: "api.openapi-docs",
      name: "OpenAPI Documentation",
      type: "api",
      summary: "Repository includes OpenAPI or Swagger documentation files.",
      source_paths: scan.discovery_files.openapi.map((file) => file.path),
      reads: ["API contract files"],
      writes: ["machine-readable API documentation"],
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "low"
    });
  }

  if (scan.discovery_files.mcp.length || scan.routes.api_routes.some((route) => route.route.includes("mcp")) || allDependencies.some((dependency) => dependency.includes("modelcontextprotocol"))) {
    seeds.push({
      id: "mcp.tool-server",
      name: "MCP Tool Server",
      type: "mcp",
      summary: "Repository contains MCP-related routes, manifests, files, or dependencies.",
      source_paths: uniqueSorted([
        ...scan.discovery_files.mcp.map((file) => file.path),
        ...scan.routes.api_routes.filter((route) => route.route.includes("mcp")).map((route) => route.source_path),
        ...packageEvidence(scan)
      ]),
      api_routes: scan.routes.api_routes.filter((route) => route.route.includes("mcp")).map((route) => `${route.methods.join("|")} ${route.route}`),
      dependencies: allDependencies.filter((dependency) => dependency.includes("modelcontextprotocol") || dependency.includes("mcp")),
      reads: ["JSON-RPC requests or MCP discovery metadata"],
      writes: ["JSON-RPC responses or MCP metadata"],
      auth_requirements: authRequirements(scan),
      confidence: "medium",
      reuse: "partial",
      extraction_difficulty: "medium"
    });
  }

  if (scan.discovery_files.sitemaps.length || scan.discovery_files.feeds.length || scan.discovery_files.robots.length || scan.discovery_files.manifests.length) {
    seeds.push({
      id: "seo.discovery-surface",
      name: "SEO and Discovery Surface",
      type: "seo",
      summary: "Repository includes crawlable discovery files such as sitemap, feeds, robots, or web manifest files.",
      source_paths: [
        ...scan.discovery_files.sitemaps,
        ...scan.discovery_files.feeds,
        ...scan.discovery_files.robots,
        ...scan.discovery_files.manifests
      ].map((file) => file.path),
      reads: ["public content metadata"],
      writes: ["crawlable discovery documents"],
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "low"
    });
  }

  if (scan.tests.length) {
    seeds.push({
      id: "testing.automated-tests",
      name: "Automated Test Suite",
      type: "testing",
      summary: "Repository includes automated test files.",
      source_paths: testPaths,
      dependencies: allDependencies.filter((dependency) => /vitest|jest|playwright|cypress|testing-library/i.test(dependency)),
      reads: ["source code under test"],
      writes: ["test results"],
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "medium"
    });
  }

  if (scan.ci.workflows.length || scan.containers.dockerfiles.length || scan.containers.compose_files.length || scan.configs.some((file) => file.path === "vercel.json")) {
    seeds.push({
      id: "deployment.project-automation",
      name: "Deployment and Project Automation",
      type: "deployment",
      summary: "Repository includes CI workflows, deployment config, or containerization files.",
      source_paths: [
        ...scan.ci.workflows,
        ...scan.containers.dockerfiles,
        ...scan.containers.compose_files,
        ...scan.configs.filter((file) => /vercel\.json|netlify|wrangler/i.test(file.path))
      ].map((file) => file.path),
      reads: ["repository source", "CI configuration"],
      writes: ["build artifacts or deployment outputs"],
      external_services: scan.integrations.map((integration) => integration.name).filter((name) => ["Vercel", "AWS"].includes(name)),
      confidence: "high",
      reuse: "pattern_only",
      extraction_difficulty: "medium"
    });
  }

  if (scan.env.variables.length) {
    seeds.push({
      id: "security.env-configuration",
      name: "Environment Configuration",
      type: "security",
      summary: "Repository references environment variables; secret-like names are cataloged without values.",
      source_paths: uniqueSorted(scan.env.variables.flatMap((variable) => variable.source_paths)),
      env_vars: envVars,
      reads: ["environment variable names"],
      writes: [],
      sensitive_data: scan.env.variables.filter((variable) => variable.likely_secret).map((variable) => variable.name),
      auth_requirements: authRequirements(scan),
      confidence: "medium",
      reuse: "pattern_only",
      extraction_difficulty: "medium",
      notes: ["Catalog stores environment variable names only, never values."]
    });
  }

  for (const integration of scan.integrations) {
    const id = integrationCapabilityId(integration.name);
    seeds.push({
      id,
      name: `${integration.name} Integration`,
      type: integrationType(integration.name),
      summary: `Repository has source-backed indicators for a ${integration.name} integration.`,
      source_paths: integration.evidence_paths,
      dependencies: allDependencies.filter((dependency) => dependency.toLowerCase().includes(integration.name.toLowerCase())),
      external_services: [integration.name],
      env_vars: envVars.filter((envVar) => envVar.toLowerCase().includes(integration.name.toLowerCase())),
      reads: [`${integration.name} configuration or SDK inputs`],
      writes: [`${integration.name} API calls or integration outputs`],
      sensitive_data: sensitiveData,
      confidence: integration.confidence,
      reuse: "partial",
      extraction_difficulty: "medium"
    });
  }

  seeds.push(...buildPatternCapabilities(scan, allDependencies, envVars, externalServices, sensitiveData));

  if (!seeds.length && (readmePaths.length || docsPaths.length || packageEvidence(scan).length)) {
    seeds.push({
      id: "other.repository-context",
      name: "Repository Context",
      type: "other",
      summary: "Repository has limited deterministic evidence; purpose requires further Codex or human review.",
      source_paths: uniqueSorted([...readmePaths, ...docsPaths, ...packageEvidence(scan), ...llmsPaths]).slice(0, MAX_EVIDENCE_PATHS),
      reads: ["repository metadata"],
      writes: [],
      confidence: readmePaths.length || llmsPaths.length ? "low" : "medium",
      reuse: "unknown",
      extraction_difficulty: "unknown"
    });
  }

  const capabilityRisks = risksForCapabilities(repositoryRisks);
  return mergeDuplicateSeeds(seeds)
    .filter((seed) => seed.source_paths.length > 0)
    .map((seed) => materializeCapability(scan, seed, docsPaths, llmsPaths, testPaths, capabilityRisks));
}

function buildPatternCapabilities(
  scan: ScanArtifact,
  allDependencies: string[],
  envVars: string[],
  externalServices: string[],
  sensitiveData: string[]
): CapabilitySeed[] {
  const evidence = searchableEvidence(scan);
  const definitions: Array<{
    id: string;
    name: string;
    type: string;
    summary: string;
    patterns: RegExp[];
    packagePatterns?: RegExp[];
    envPatterns?: RegExp[];
    reads?: string[];
    writes?: string[];
    sensitive?: string[];
    reuse?: CapabilitySeed["reuse"];
  }> = [
    {
      id: "auth.user-session",
      name: "User Authentication and Sessions",
      type: "authentication",
      summary: "Source evidence indicates authentication, login, session, token, or identity handling.",
      patterns: [/auth/i, /login/i, /logout/i, /session/i, /jwt/i, /oauth/i, /callback/i],
      packagePatterns: [/next-auth/i, /clerk/i, /auth0/i, /passport/i, /lucia/i],
      envPatterns: [/AUTH/i, /SESSION/i, /JWT/i, /CLERK/i, /OAUTH/i],
      reads: ["credentials, identity provider callbacks, or session state"],
      writes: ["session or authentication responses"],
      sensitive: ["email", "password", "session_token", "OAuth tokens"]
    },
    {
      id: "authorization.access-control",
      name: "Access Control",
      type: "authorization",
      summary: "Source evidence indicates roles, permissions, admin boundaries, or access-control checks.",
      patterns: [/rbac/i, /permission/i, /role/i, /admin/i, /authorize/i, /access-control/i],
      reads: ["user role or permission state"],
      writes: ["authorization decisions"],
      sensitive: ["user profile data"]
    },
    {
      id: "webhooks.event-receiver",
      name: "Webhook Event Receiver",
      type: "webhooks",
      summary: "Source evidence indicates webhook receiving, event delivery, or signature validation behavior.",
      patterns: [/webhook/i, /signature/i, /event.*route/i],
      envPatterns: [/WEBHOOK/i, /SIGNING_SECRET/i],
      reads: ["webhook request payloads", "signature headers"],
      writes: ["event handling responses"],
      sensitive: ["webhook secrets"],
      reuse: "partial"
    },
    {
      id: "dashboard.operational-dashboard",
      name: "Operational Dashboard",
      type: "dashboard",
      summary: "Source evidence indicates dashboard, admin, status, or overview UI surfaces.",
      patterns: [/dashboard/i, /admin/i, /overview/i, /status/i, /metrics/i],
      reads: ["status, metric, or summary data"],
      writes: ["rendered dashboard UI"],
      reuse: "pattern_only"
    },
    {
      id: "analytics.metrics-reporting",
      name: "Metrics and Reporting",
      type: "analytics",
      summary: "Source evidence indicates analytics, metrics, reports, scores, or aggregation behavior.",
      patterns: [/analytics/i, /metrics/i, /report/i, /score/i, /aggregation/i, /insight/i],
      reads: ["events, metrics, or report inputs"],
      writes: ["aggregated reports or analytics views"],
      reuse: "partial"
    },
    {
      id: "search.query-interface",
      name: "Search Query Interface",
      type: "search",
      summary: "Source evidence indicates search UI, indexing, or query behavior.",
      patterns: [/search/i, /query/i],
      packagePatterns: [/algolia/i, /meilisearch/i, /lunr/i, /fuse\.js/i, /flexsearch/i],
      reads: ["query input", "indexed content"],
      writes: ["search results"],
      reuse: "partial"
    },
    {
      id: "file.upload-handling",
      name: "File Upload Handling",
      type: "file-upload",
      summary: "Source evidence indicates upload, attachment, media, or multipart file handling.",
      patterns: [/upload/i, /attachment/i, /multipart/i, /media/i, /blob/i],
      packagePatterns: [/multer/i, /uploadthing/i, /@vercel\/blob/i],
      reads: ["uploaded files or media metadata"],
      writes: ["stored files or upload responses"],
      sensitive: ["user file contents"],
      reuse: "partial"
    },
    {
      id: "content.publishing-workflow",
      name: "Content Publishing Workflow",
      type: "content-management",
      summary: "Source evidence indicates content, docs, posts, publishing, CMS, or markdown/MDX workflows.",
      patterns: [/content/i, /cms/i, /post/i, /blog/i, /docs/i, /mdx/i, /publish/i, /article/i],
      packagePatterns: [/contentlayer/i, /fumadocs/i, /gray-matter/i, /mdx/i],
      reads: ["content source files or editorial metadata"],
      writes: ["published content pages or feeds"],
      reuse: "partial"
    },
    {
      id: "forms.submission-flow",
      name: "Form Submission Flow",
      type: "forms",
      summary: "Source evidence indicates forms, contact flows, submit endpoints, or validation-backed input handling.",
      patterns: [/form/i, /submit/i, /contact/i, /lead/i, /intake/i],
      packagePatterns: [/react-hook-form/i, /formik/i],
      reads: ["form input"],
      writes: ["submission records or responses"],
      sensitive: ["email", "user profile data"]
    },
    {
      id: "ai.chat-or-generation",
      name: "AI Chat or Generation",
      type: "ai-model",
      summary: "Source evidence indicates AI model, chat, completion, prompt, or generation behavior.",
      patterns: [/\bai\b/i, /chat/i, /prompt/i, /completion/i, /generate/i],
      packagePatterns: [/openai/i, /anthropic/i, /^ai$/i, /langchain/i],
      envPatterns: [/OPENAI/i, /ANTHROPIC/i, /MODEL/i],
      reads: ["prompts, messages, or generation inputs"],
      writes: ["model outputs or generated artifacts"],
      sensitive: ["user prompts", "API keys"],
      reuse: "partial"
    },
    {
      id: "observability.trace-logging",
      name: "Trace and Logging",
      type: "observability",
      summary: "Source evidence indicates trace, span, logging, monitoring, or OpenTelemetry behavior.",
      patterns: [/trace/i, /span/i, /log/i, /monitor/i, /health/i, /otel/i, /observability/i],
      packagePatterns: [/opentelemetry/i, /pino/i, /winston/i],
      reads: ["request or runtime metadata"],
      writes: ["logs, spans, health responses, or monitoring data"],
      sensitive: ["IP address", "request fingerprints"],
      reuse: "partial"
    },
    {
      id: "automation.workflow-runner",
      name: "Workflow Runner",
      type: "automation",
      summary: "Source evidence indicates jobs, workflows, queues, cron tasks, or automation runs.",
      patterns: [/workflow/i, /job/i, /queue/i, /cron/i, /automation/i, /runner/i, /task/i],
      packagePatterns: [/bullmq/i, /inngest/i, /trigger/i, /agenda/i],
      reads: ["workflow inputs or queued jobs"],
      writes: ["workflow run state or task outputs"],
      reuse: "partial"
    },
    {
      id: "data.import-export",
      name: "Data Import and Export",
      type: "data-export",
      summary: "Source evidence indicates import, export, CSV, JSON, XML, or structured data transfer behavior.",
      patterns: [/import/i, /export/i, /\bcsv\b/i, /\bjson\b/i, /\bxml\b/i, /download/i],
      packagePatterns: [/csv/i, /xlsx/i, /papaparse/i],
      reads: ["structured data input"],
      writes: ["structured data output"],
      reuse: "partial"
    },
    {
      id: "document.processing",
      name: "Document Processing",
      type: "document-processing",
      summary: "Source evidence indicates PDF, DOCX, document conversion, extraction, or rendering behavior.",
      patterns: [/document/i, /\bpdf\b/i, /\bdocx\b/i, /extract/i, /render/i],
      packagePatterns: [/pdf/i, /docx/i, /mammoth/i],
      reads: ["document files or document metadata"],
      writes: ["processed document outputs"],
      sensitive: ["document contents"],
      reuse: "partial"
    },
    {
      id: "gameplay.browser-game",
      name: "Browser Gameplay",
      type: "gameplay",
      summary: "Source evidence indicates game, canvas, realtime, player, or gameplay implementation.",
      patterns: [/game/i, /player/i, /score/i, /canvas/i, /level/i, /sprite/i, /multiplayer/i],
      packagePatterns: [/phaser/i, /three/i, /pixi/i],
      reads: ["player input or game state"],
      writes: ["rendered gameplay or score state"],
      reuse: "partial"
    },
    {
      id: "ecommerce.product-catalog",
      name: "Ecommerce Product Catalog",
      type: "ecommerce",
      summary: "Source evidence indicates products, cart, checkout, orders, Shopify, or commerce flows.",
      patterns: [/product/i, /cart/i, /checkout/i, /order/i, /shopify/i, /commerce/i],
      packagePatterns: [/shopify/i, /commerce/i],
      envPatterns: [/SHOPIFY/i],
      reads: ["product, cart, or order data"],
      writes: ["commerce UI or checkout/order responses"],
      sensitive: ["payment data", "user profile data"],
      reuse: "partial"
    },
    {
      id: "shipping.fulfillment-flow",
      name: "Shipping and Fulfillment Flow",
      type: "shipping",
      summary: "Source evidence indicates shipping, labels, postcards, fulfillment, or delivery-provider integration.",
      patterns: [/shipping/i, /shipment/i, /label/i, /postcard/i, /fulfillment/i, /stannp/i],
      envPatterns: [/STANNP/i, /SHIP/i],
      reads: ["recipient or shipment details"],
      writes: ["shipping labels, postcards, or fulfillment requests"],
      sensitive: ["location data", "user profile data"],
      reuse: "partial"
    },
    {
      id: "finance.financial-workflow",
      name: "Financial Workflow",
      type: "finance",
      summary: "Source evidence indicates finance, invoices, billing, payments, revenue, or market data behavior.",
      patterns: [/finance/i, /invoice/i, /billing/i, /revenue/i, /payment/i, /polymarket/i],
      reads: ["financial or billing data"],
      writes: ["financial reports or payment workflow outputs"],
      sensitive: ["financial data", "payment data"],
      reuse: "partial"
    },
    {
      id: "dictionary.lookup-tools",
      name: "Dictionary Lookup Tools",
      type: "dictionary",
      summary: "Source evidence indicates dictionary, glossary, lookup, or terminology tooling.",
      patterns: [/dictionary/i, /glossary/i, /lookup/i, /term/i],
      reads: ["terms or query input"],
      writes: ["definitions or lookup results"],
      reuse: "pattern_only"
    },
    {
      id: "accessibility.ui-a11y",
      name: "Accessibility UI Support",
      type: "accessibility",
      summary: "Source evidence indicates ARIA, accessibility, keyboard, or screen-reader oriented UI behavior.",
      patterns: [/aria-/i, /accessibility/i, /a11y/i, /screen-reader/i, /keyboard/i],
      reads: ["UI interaction state"],
      writes: ["accessible UI attributes or controls"],
      reuse: "pattern_only"
    }
  ];

  const seeds: CapabilitySeed[] = [];
  for (const definition of definitions) {
    const matchedPaths = new Set<string>();
    const matchedSignals: string[] = [];
    for (const item of evidence) {
      if (definition.patterns.some((pattern) => pattern.test(item.text))) {
        matchedPaths.add(item.path);
        matchedSignals.push(item.text);
      }
    }
    if (definition.packagePatterns) {
      const matchedPackages = allDependencies.filter((dependency) => definition.packagePatterns?.some((pattern) => pattern.test(dependency)));
      if (matchedPackages.length) {
        for (const packagePath of packageEvidence(scan)) matchedPaths.add(packagePath);
        matchedSignals.push(...matchedPackages);
      }
    }
    if (definition.envPatterns) {
      const matchedEnv = envVars.filter((envVar) => definition.envPatterns?.some((pattern) => pattern.test(envVar)));
      if (matchedEnv.length) {
        for (const variable of scan.env.variables.filter((variable) => matchedEnv.includes(variable.name))) {
          for (const sourcePath of variable.source_paths) matchedPaths.add(sourcePath);
        }
        matchedSignals.push(...matchedEnv);
      }
    }
    const source_paths = uniqueSorted(matchedPaths).slice(0, MAX_EVIDENCE_PATHS);
    if (!source_paths.length) continue;
    const codeBacked = source_paths.some((sourcePath) => /\.(ts|tsx|js|jsx|svelte|vue|astro|py|go|rs|rb|php)$/i.test(sourcePath));
    seeds.push({
      id: definition.id,
      name: definition.name,
      type: definition.type,
      summary: definition.summary,
      source_paths,
      dependencies: allDependencies.filter((dependency) => definition.packagePatterns?.some((pattern) => pattern.test(dependency))),
      external_services: externalServices.filter((service) => matchedSignals.some((signal) => signal.toLowerCase().includes(service.toLowerCase()))),
      env_vars: envVars.filter((envVar) => definition.envPatterns?.some((pattern) => pattern.test(envVar))),
      reads: definition.reads,
      writes: definition.writes,
      sensitive_data: uniqueSorted([...(definition.sensitive ?? []), ...sensitiveData.filter((data) => matchedSignals.some((signal) => signal.toLowerCase().includes(data.toLowerCase())))]),
      confidence: codeBacked ? "medium" : "low",
      reuse: definition.reuse ?? "pattern_only",
      extraction_difficulty: codeBacked ? "medium" : "unknown",
      notes: ["Pattern capability generated from deterministic file, route, dependency, or environment-name evidence."]
    });
  }
  return seeds;
}

function searchableEvidence(scan: ScanArtifact): Array<{ text: string; path: string }> {
  const evidence: Array<{ text: string; path: string }> = [];
  for (const route of [...scan.routes.api_routes, ...scan.routes.app_routes]) {
    evidence.push({ text: `${route.route} ${route.kind} ${route.source_path}`, path: route.source_path });
  }
  for (const component of scan.components) evidence.push({ text: `${component.name} ${component.kind} ${component.source_path}`, path: component.source_path });
  for (const model of scan.data_models) evidence.push({ text: `${model.name} ${model.kind} ${model.source_path}`, path: model.source_path });
  for (const file of [...scan.docs.readme_paths, ...scan.docs.doc_paths, ...scan.docs.llms_context_paths, ...scan.configs]) {
    evidence.push({ text: file.path, path: file.path });
  }
  for (const manifest of scan.packages.manifests) {
    evidence.push({ text: `${manifest.name ?? ""} ${Object.keys(manifest.scripts).join(" ")} ${Object.keys(manifest.dependencies).join(" ")} ${Object.keys(manifest.dev_dependencies).join(" ")}`, path: manifest.path });
  }
  for (const variable of scan.env.variables) {
    for (const sourcePath of variable.source_paths) evidence.push({ text: `${variable.name} ${sourcePath}`, path: sourcePath });
  }
  for (const integration of scan.integrations) {
    for (const sourcePath of integration.evidence_paths) evidence.push({ text: `${integration.name} ${sourcePath}`, path: sourcePath });
  }
  return evidence;
}

function materializeCapability(
  scan: ScanArtifact,
  seed: CapabilitySeed,
  docsPaths: string[],
  llmsPaths: string[],
  testPaths: string[],
  capabilityRisks: RiskManifest[]
): CapabilityManifest {
  const sourcePaths = uniqueSorted(seed.source_paths).slice(0, MAX_EVIDENCE_PATHS);
  const frameworkCoupling = scan.frameworks.length ? "medium" : "unknown";
  const databaseCoupling = scan.database.databases.length ? "high" : "low";
  const externalCoupling = seed.external_services?.length || scan.integrations.length ? "medium" : "low";
  const authCoupling = authRequirements(scan).length ? "medium" : "low";
  const confidence = seed.confidence ?? inferCapabilityConfidence(sourcePaths, testPaths, docsPaths);
  const reusableLevel = seed.reuse ?? (confidence === "high" ? "partial" : "pattern_only");

  return {
    id: seed.id,
    name: seed.name,
    type: seed.type,
    summary: seed.summary,
    maturity: seed.maturity ?? inferCapabilityMaturity(scan, sourcePaths),
    reusable: reusableLevel === "full" || reusableLevel === "partial" || reusableLevel === "pattern_only",
    confidence,
    source_paths: sourcePaths,
    interfaces: {
      api_routes: uniqueSorted(seed.api_routes ?? []),
      ui_components: uniqueSorted(seed.ui_components ?? []),
      cli_commands: [],
      events: [],
      exports: [],
      inputs: uniqueSorted(seed.reads ?? []),
      outputs: uniqueSorted(seed.writes ?? [])
    },
    data_handling: {
      reads: uniqueSorted(seed.reads ?? []),
      writes: uniqueSorted(seed.writes ?? []),
      sensitive_data: uniqueSorted(seed.sensitive_data ?? []),
      external_data_flows: uniqueSorted(seed.external_services ?? []),
      persistence_layer: uniqueSorted(seed.persistence_layer ?? scan.database.databases),
      validation: uniqueSorted(seed.validation ?? []),
      auth_requirements: uniqueSorted(seed.auth_requirements ?? []),
      privacy_security_notes: privacyNotes(seed)
    },
    dependencies: {
      packages: uniqueSorted(seed.dependencies ?? []),
      internal: [],
      external_services: uniqueSorted(seed.external_services ?? []),
      env_vars: uniqueSorted(seed.env_vars ?? [])
    },
    reuse: {
      reusable: reusableLevel,
      extraction_difficulty: seed.extraction_difficulty ?? inferExtractionDifficulty(scan, seed),
      coupling: {
        framework: frameworkCoupling,
        database: databaseCoupling,
        external_services: externalCoupling,
        auth: authCoupling
      },
      recommended_reuse_approach: recommendedReuseApproach(seed, reusableLevel),
      extraction_steps: extractionSteps(seed),
      notes: seed.notes ?? []
    },
    risks: capabilityRisks.filter((risk) => risk.evidence_paths.some((evidencePath) => sourcePaths.includes(evidencePath))).slice(0, 20),
    tests: {
      has_tests: testPaths.length > 0,
      test_paths: testPaths.slice(0, 30),
      notes: testPaths.length ? ["Repository has test evidence; verify capability-specific coverage before extraction."] : ["No repository test files were detected for this capability."]
    },
    docs: {
      readme: scan.docs.readme_paths.length > 0,
      docs_paths: docsPaths.slice(0, 30),
      llms_context_paths: llmsPaths.slice(0, 20),
      notes: llmsPaths.length ? ["LLMs files are available as supplementary context."] : []
    },
    related_capabilities: [],
    notes: seed.notes ?? []
  };
}

function mergeDuplicateSeeds(seeds: CapabilitySeed[]): CapabilitySeed[] {
  const byId = new Map<string, CapabilitySeed>();
  for (const seed of seeds) {
    const existing = byId.get(seed.id);
    if (!existing) {
      byId.set(seed.id, { ...seed, source_paths: uniqueSorted(seed.source_paths) });
      continue;
    }
    byId.set(seed.id, {
      ...existing,
      source_paths: uniqueSorted([...existing.source_paths, ...seed.source_paths]),
      dependencies: uniqueSorted([...(existing.dependencies ?? []), ...(seed.dependencies ?? [])]),
      external_services: uniqueSorted([...(existing.external_services ?? []), ...(seed.external_services ?? [])]),
      env_vars: uniqueSorted([...(existing.env_vars ?? []), ...(seed.env_vars ?? [])]),
      api_routes: uniqueSorted([...(existing.api_routes ?? []), ...(seed.api_routes ?? [])]),
      ui_components: uniqueSorted([...(existing.ui_components ?? []), ...(seed.ui_components ?? [])])
    });
  }
  return [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));
}

function inferDescription(scan: ScanArtifact): string {
  const readme = scan.docs.readme_paths[0]?.path;
  if (readme) {
    const description = extractDescriptionFromText(readTextSafe(path.join(scan.repo.path, readme)));
    if (description) return description;
  }
  const llms = scan.docs.llms_context_paths[0]?.path;
  if (llms) {
    const description = extractDescriptionFromText(readTextSafe(path.join(scan.repo.path, llms)));
    if (description) return description;
  }
  if (scan.packages.manifests[0]?.name) return `Package repository for ${scan.packages.manifests[0].name}.`;
  return `Repository ${scan.repo.name}; purpose requires further source review.`;
}

function extractDescriptionFromText(text: string): string | null {
  const lines = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("!") && !line.startsWith("[!["));
  const h1 = lines.find((line) => line.startsWith("# "));
  const paragraph = lines.find((line) => !line.startsWith("#") && !line.startsWith("---") && !line.startsWith("```"));
  const raw = paragraph ?? h1?.replace(/^#\s+/, "") ?? null;
  return raw ? raw.slice(0, 500) : null;
}

function inferRepoMaturity(scan: ScanArtifact): Maturity {
  if (/deprecated|archive/i.test(scan.repo.name) || scan.comments.some((comment) => comment.kind === "deprecated")) return "deprecated";
  const hasTests = scan.tests.length > 0;
  const hasCi = scan.ci.workflows.length > 0;
  const hasDocs = scan.docs.readme_paths.length > 0 || scan.docs.doc_paths.length > 0 || scan.docs.llms_context_paths.length > 0;
  const hasBuildScript = scan.packages.manifests.some((manifest) => Boolean(manifest.scripts.build));
  const hasRoutesOrPackage = scan.routes.api_routes.length > 0 || scan.routes.app_routes.length > 0 || scan.packages.manifests.length > 0;
  if (hasTests && hasCi && hasDocs && hasBuildScript) return "production";
  if (hasRoutesOrPackage && (hasTests || hasCi || hasDocs)) return "internal";
  if (hasRoutesOrPackage || scan.languages.length > 0) return "prototype";
  return "unknown";
}

function inferRepoConfidence(scan: ScanArtifact): Confidence {
  if (scan.languages.length && (scan.routes.api_routes.length || scan.routes.app_routes.length || scan.packages.manifests.length)) return "high";
  if (scan.languages.length || scan.docs.readme_paths.length || scan.docs.llms_context_paths.length) return "medium";
  return "low";
}

function inferCapabilityMaturity(scan: ScanArtifact, sourcePaths: string[]): Maturity {
  const repoMaturity = inferRepoMaturity(scan);
  if (repoMaturity === "production" && scan.tests.length && sourcePaths.some((sourcePath) => !sourcePath.toLowerCase().includes("readme"))) return "internal";
  return repoMaturity === "production" ? "internal" : repoMaturity;
}

function inferCapabilityConfidence(sourcePaths: string[], testPaths: string[], docsPaths: string[]): Confidence {
  const codeEvidence = sourcePaths.some((sourcePath) => /\.(ts|tsx|js|jsx|py|go|rs|rb|php|svelte|vue|astro|sql|prisma)$/i.test(sourcePath));
  if (codeEvidence && testPaths.length) return "high";
  if (codeEvidence || docsPaths.length) return "medium";
  return "low";
}

function inferDeployment(scan: ScanArtifact): string[] {
  const deployment = new Set<string>();
  if (scan.configs.some((file) => file.path === "vercel.json") || scan.integrations.some((integration) => integration.name === "Vercel")) deployment.add("vercel");
  if (scan.containers.dockerfiles.length) deployment.add("docker");
  if (scan.ci.workflows.length) deployment.add("github-actions");
  if (scan.configs.some((file) => /netlify/i.test(file.path))) deployment.add("netlify");
  if (scan.configs.some((file) => /wrangler/i.test(file.path))) deployment.add("cloudflare");
  return uniqueSorted(deployment);
}

function inferMissingEvidence(scan: ScanArtifact): string[] {
  const missing: string[] = [];
  if (!scan.docs.readme_paths.length) missing.push("README not detected");
  if (!scan.tests.length) missing.push("test files not detected");
  if (!scan.ci.workflows.length) missing.push("CI workflows not detected");
  if (!scan.docs.llms_context_paths.length) missing.push("LLMs context files not detected");
  if (!scan.routes.api_routes.length && !scan.routes.app_routes.length) missing.push("framework route files not detected");
  return missing;
}

function buildRepositoryRisks(scan: ScanArtifact): RiskManifest[] {
  const risks: RiskManifest[] = [];
  if (scan.security.secret_risks.length) {
    risks.push({
      id: "security.secret-like-values",
      severity: "critical",
      summary: "Secret-like literal values were detected in source. Samples are redacted in scan output.",
      evidence_paths: uniqueSorted(scan.security.secret_risks.map((risk) => risk.source_path)),
      recommendation: "Remove committed credentials, rotate affected secrets, and keep only variable names in catalog outputs."
    });
  }
  if (scan.security.unsafe_patterns.length) {
    risks.push({
      id: "security.unsafe-patterns",
      severity: "medium",
      summary: "Unsafe-code or SSRF-review patterns were detected and need human review.",
      evidence_paths: uniqueSorted(scan.security.unsafe_patterns.flatMap((risk) => risk.evidence_paths)),
      recommendation: "Review input validation, sandboxing, escaping, and network allowlists before reuse."
    });
  }
  if (scan.env.variables.some((variable) => variable.likely_secret)) {
    risks.push({
      id: "security.secret-env-vars",
      severity: "medium",
      summary: "Secret-like environment variable names are referenced.",
      evidence_paths: uniqueSorted(scan.env.variables.filter((variable) => variable.likely_secret).flatMap((variable) => variable.source_paths)),
      recommendation: "Preserve variable names only in catalog outputs and verify runtime secret handling before extraction."
    });
  }
  if (!scan.tests.length) {
    const evidence = firstAvailableEvidence(scan);
    if (evidence.length) {
      risks.push({
        id: "quality.missing-tests",
        severity: "medium",
        summary: "No automated test files were detected.",
        evidence_paths: evidence,
        recommendation: "Add focused tests before treating capabilities as production-ready reuse candidates."
      });
    }
  }
  return risks.filter((risk) => risk.evidence_paths.length > 0);
}

function firstAvailableEvidence(scan: ScanArtifact): string[] {
  return uniqueSorted([
    ...scan.docs.readme_paths.map((file) => file.path),
    ...packageEvidence(scan),
    ...scan.routes.api_routes.map((route) => route.source_path),
    ...scan.routes.app_routes.map((route) => route.source_path),
    ...scan.docs.llms_context_paths.map((file) => file.path)
  ]).slice(0, 10);
}

function risksForCapabilities(risks: RiskManifest[]): RiskManifest[] {
  return risks.filter((risk) => risk.id !== "quality.missing-tests");
}

function packageEvidence(scan: ScanArtifact): string[] {
  return scan.packages.manifests.map((manifest) => manifest.path);
}

function mergedPackageNames(scan: ScanArtifact): string[] {
  const packages = new Set<string>();
  for (const manifest of scan.packages.manifests) {
    for (const name of Object.keys(manifest.dependencies)) packages.add(name);
    for (const name of Object.keys(manifest.dev_dependencies)) packages.add(name);
  }
  return uniqueSorted(packages);
}

function authRequirements(scan: ScanArtifact): string[] {
  const envNames = scan.env.variables.map((variable) => variable.name);
  const auth: string[] = [];
  if (envNames.includes("PLATPHORM_API_KEY")) auth.push("PLATPHORM_API_KEY");
  if (envNames.some((name) => /AUTH|SESSION|JWT|CLERK|NEXTAUTH/i.test(name))) auth.push("auth/session environment variables");
  if (mergedPackageNames(scan).some((dependency) => /next-auth|clerk|auth0|passport|lucia/i.test(dependency))) auth.push("auth framework dependency");
  return uniqueSorted(auth);
}

function privacyNotes(seed: CapabilitySeed): string[] {
  const notes: string[] = [];
  if (seed.sensitive_data?.length) notes.push("Sensitive-data indicators require validation before reuse.");
  if (seed.env_vars?.some((name) => /SECRET|TOKEN|KEY|PASSWORD/i.test(name))) notes.push("Secret-like environment variables are referenced by name only.");
  if (seed.external_services?.length) notes.push("External service flows require credential, privacy, and data-retention review.");
  return notes;
}

function recommendedReuseApproach(seed: CapabilitySeed, reusableLevel: CapabilityManifest["reuse"]["reusable"]): string {
  if (reusableLevel === "not_recommended") return "Do not reuse until the flagged risks are resolved.";
  if (reusableLevel === "unknown") return "Use only as a review target until source behavior is inspected.";
  if (reusableLevel === "pattern_only") return "Reuse the implementation pattern after recreating it in the target project's framework and test harness.";
  return "Extract the source-backed files with their dependencies, then add tests around the target integration boundary.";
}

function extractionSteps(seed: CapabilitySeed): string[] {
  return [
    "Review all listed source paths.",
    "Copy only source-backed implementation files and required local dependencies.",
    "Replace repository-specific configuration, routes, and environment variable handling.",
    "Add tests that prove the capability in the target project.",
    ...(seed.external_services?.length ? ["Verify external service credentials, webhook signatures, rate limits, and data-retention behavior."] : [])
  ];
}

function inferExtractionDifficulty(scan: ScanArtifact, seed: CapabilitySeed): CapabilityManifest["reuse"]["extraction_difficulty"] {
  if (seed.external_services?.length || scan.database.databases.length) return "high";
  if (scan.frameworks.length || seed.source_paths.length > 10) return "medium";
  return "low";
}

function integrationCapabilityId(name: string): string {
  const normalized = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const domain = integrationType(name) === "payments" ? "payments" : integrationType(name) === "email" ? "email" : "integration";
  return `${domain}.${normalized}`;
}

function integrationType(name: string): string {
  if (/stripe/i.test(name)) return "payments";
  if (/gmail|stannp/i.test(name)) return "email";
  if (/mcp/i.test(name)) return "mcp";
  if (/openai|anthropic/i.test(name)) return "ai-model";
  return "integration";
}
